/**
 * Base docker-compose template: OpenClaw + API Proxy (builtin processor).
 * Security: API key isolated in proxy, read-only rootfs, resource limits, PII filtering.
 */
export function baseComposeTemplate(name: string, port: number): string {
  return `# Generated by claw-farm — ${name}
services:
  api-proxy:
    build: ./api-proxy
    expose:
      - "8080"
    environment:
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      AUDIT_LOG_PATH: /logs/api-proxy-audit.jsonl
      MAX_PROMPT_SIZE_MB: 5
      PII_MODE: redact  # redact | block | warn
    volumes:
      - ./logs:/logs
    networks:
      - proxy-net
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "127.0.0.1:${port}:18789"
    volumes:
      # Config files mounted individually (OpenClaw needs to write temp files in .openclaw/)
      - ./openclaw/config/openclaw.json5:/home/node/.openclaw/openclaw.json5:ro
      - ./openclaw/config/policy.yaml:/home/node/.openclaw/policy.yaml:ro
      - ./openclaw/workspace:/home/node/.openclaw/workspace
      - ./openclaw/raw/sessions:/home/node/.openclaw/sessions
      - openclaw-logs:/home/node/.openclaw/logs
    environment:
      # No GEMINI_API_KEY here — agent cannot see it
      OPENCLAW_API_PROXY: http://api-proxy:8080
      OPENCLAW_SANDBOX: 1
      OPENCLAW_AUDIT_LOG: /home/node/.openclaw/logs/audit.jsonl
    networks:
      - proxy-net
    read_only: true
    tmpfs:
      - /tmp:size=100M
      - /home/node/.cache:size=200M
      - /home/node/.openclaw:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 128M
    depends_on:
      api-proxy:
        condition: service_healthy
    restart: unless-stopped

networks:
  proxy-net:
    internal: true

volumes:
  openclaw-logs:
`;
}
