/**
 * Per-instance docker-compose template for multi-instance projects.
 * Shared template files mounted read-only, per-instance data mounted read-write.
 */
export function instanceComposeTemplate(
  projectName: string,
  userId: string,
  port: number,
): string {
  const containerPrefix = `${projectName}-${userId}`;
  return `# Generated by claw-farm — ${projectName} instance: ${userId}
services:
  api-proxy:
    container_name: ${containerPrefix}-api-proxy
    build: ../../api-proxy
    expose:
      - "8080"
    env_file:
      - ../../.env
    environment:
      AUDIT_LOG_PATH: /logs/api-proxy-audit.jsonl
      MAX_PROMPT_SIZE_MB: 5
      PII_MODE: redact
    volumes:
      - ./logs:/logs
    networks:
      - proxy-net
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  openclaw-gateway:
    container_name: ${containerPrefix}-openclaw
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "127.0.0.1:${port}:18789"
    volumes:
      # Shared config files (read-only, mounted individually to avoid shadowing)
      - ../../template/config/openclaw.json:/home/node/.openclaw/openclaw.json:ro
      - ../../template/config/policy.yaml:/home/node/.openclaw/policy.yaml:ro
      # Shared template files (read-only)
      - ../../template/SOUL.md:/home/node/.openclaw/workspace/SOUL.md:ro
      - ../../template/AGENTS.md:/home/node/.openclaw/workspace/AGENTS.md:ro
      - ../../template/skills:/home/node/.openclaw/workspace/skills:ro
      # Per-instance files (read-write)
      - ./USER.md:/home/node/.openclaw/workspace/USER.md
      - ./MEMORY.md:/home/node/.openclaw/workspace/MEMORY.md
      - ./memory:/home/node/.openclaw/workspace/memory
      - ./raw/sessions:/home/node/.openclaw/sessions
      - ./logs:/home/node/.openclaw/logs
    environment:
      OPENCLAW_API_PROXY: http://api-proxy:8080
      OPENCLAW_SANDBOX: 1
      OPENCLAW_AUDIT_LOG: /home/node/.openclaw/logs/audit.jsonl
    networks:
      - proxy-net
    read_only: true
    tmpfs:
      - /tmp:size=100M
      - /home/node/.cache:size=200M
      - /home/node/.openclaw:size=50M,uid=1000,gid=1000
      - /home/node/.openclaw/workspace:size=10M,uid=1000,gid=1000
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 256M
    depends_on:
      api-proxy:
        condition: service_healthy
    restart: unless-stopped

networks:
  proxy-net:
    # internal: false — allows port binding + outbound for api-proxy
    # Production deploys use cloud:compose with nginx + full network isolation
`;
}
