import type { ProxyMode } from "../runtimes/interface.ts";
import { safeYamlIdentifier } from "../lib/validate.ts";

/**
 * Per-instance docker-compose template for multi-instance projects.
 * Shared template files mounted read-only, per-instance data mounted read-write.
 */
export function instanceComposeTemplate(
  projectName: string,
  userId: string,
  port: number,
  proxyMode: ProxyMode = "per-instance",
): string {
  safeYamlIdentifier(projectName, "project name");
  safeYamlIdentifier(userId, "user ID");
  const containerPrefix = `${projectName}-${userId}`;
  const hasProxy = proxyMode !== "none";
  return `# Generated by claw-farm — ${projectName} instance: ${userId}
services:
${hasProxy ? `  api-proxy:
    container_name: ${containerPrefix}-api-proxy
    build: ../../api-proxy
    expose:
      - "8080"
    env_file:
      - ../../.env
    environment:
      AUDIT_LOG_PATH: /logs/api-proxy-audit.jsonl
      MAX_PROMPT_SIZE_MB: 5
      PII_MODE: redact
    volumes:
      - ./logs:/logs
    networks:
      - proxy-net
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

` : ""}  openclaw-gateway:
    container_name: ${containerPrefix}-openclaw
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "127.0.0.1:${port}:18789"
    volumes:
      # Directory mount — OpenClaw needs atomic rename for config updates
      # Template files (SOUL.md, AGENTS.md, skills/) are copied into openclaw/workspace/
      # at spawn/upgrade time instead of overlay mounts (Docker Desktop compatibility)
      - ./openclaw:/home/node/.openclaw
    environment:
${hasProxy ? `      OPENCLAW_API_PROXY: http://api-proxy:8080` : `      # OPENCLAW_API_PROXY: not set (proxyMode: none)`}
      OPENCLAW_SANDBOX: 1
      OPENCLAW_AUDIT_LOG: /home/node/.openclaw/logs/audit.jsonl
${hasProxy ? `    networks:
      - proxy-net` : ""}
    read_only: true
    tmpfs:
      - /tmp:size=100M
      - /home/node/.cache:size=200M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 256M
${hasProxy ? `    depends_on:
      api-proxy:
        condition: service_healthy` : ""}
    restart: unless-stopped
${hasProxy ? `
networks:
  proxy-net:
    # internal: false — allows port binding + outbound for api-proxy
    # Production deploys use cloud:compose with nginx + full network isolation` : ""}
`;
}
