import type { ProxyMode } from "../runtimes/interface.ts";

/**
 * Base docker-compose template: OpenClaw + API Proxy (builtin processor).
 * Security: API key isolated in proxy, read-only rootfs, resource limits, PII filtering.
 */
export function baseComposeTemplate(name: string, port: number, proxyMode: ProxyMode = "per-instance"): string {
  const hasProxy = proxyMode !== "none";
  return `# Generated by claw-farm — ${name}
services:
${hasProxy ? `  api-proxy:
    build: ./api-proxy
    expose:
      - "8080"
    environment:
      LLM_PROVIDER: \${LLM_PROVIDER:-gemini}
      GEMINI_API_KEY: \${GEMINI_API_KEY:-}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:-}
      OPENAI_API_KEY: \${OPENAI_API_KEY:-}
      OPENAI_COMPAT_BASE_URL: \${OPENAI_COMPAT_BASE_URL:-}
      AUDIT_LOG_PATH: /logs/api-proxy-audit.jsonl
      MAX_PROMPT_SIZE_MB: 5
      PII_MODE: redact  # redact | block | warn
    volumes:
      - ./logs:/logs
    networks:
      - proxy-net
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

` : ""}  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "127.0.0.1:${port}:18789"
    volumes:
      # Directory mount — OpenClaw needs atomic rename for config updates
      - ./openclaw:/home/node/.openclaw
    environment:
      # No GEMINI_API_KEY here — agent cannot see it
${hasProxy ? `      OPENCLAW_API_PROXY: http://api-proxy:8080` : `      # OPENCLAW_API_PROXY: not set (proxyMode: none)`}
      OPENCLAW_SANDBOX: 1
      OPENCLAW_AUDIT_LOG: /home/node/.openclaw/logs/audit.jsonl
${hasProxy ? `    networks:
      - proxy-net` : ""}
    read_only: true
    tmpfs:
      - /tmp:size=100M
      - /home/node/.cache:size=200M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 256M
${hasProxy ? `    depends_on:
      api-proxy:
        condition: service_healthy` : ""}
    restart: unless-stopped
${hasProxy ? `
networks:
  proxy-net:
    # internal: false — allows port binding + outbound for api-proxy
    # Production deploys use cloud:compose with nginx + full network isolation` : ""}
`;
}
