import type { ProxyMode } from "../runtimes/interface.ts";
import { safeYamlIdentifier } from "../lib/validate.ts";

const HERMES_IMAGE = "nousresearch/hermes-agent:latest";
const HERMES_API_PORT = 8642;

function hermesEnvironment(indent = "      ", gatewayAllowAllUsers = false): string {
  return [
    `${indent}HERMES_HOME: /opt/data`,
    `${indent}API_SERVER_ENABLED: "true"`,
    `${indent}API_SERVER_HOST: 0.0.0.0`,
    `${indent}API_SERVER_KEY: \${API_SERVER_KEY:?Set API_SERVER_KEY for Hermes API access}`,
    `${indent}GATEWAY_ALLOW_ALL_USERS: "${gatewayAllowAllUsers ? "true" : "false"}"`,
  ].join("\n");
}

function healthcheck(indent = "    "): string {
  return `${indent}healthcheck:
${indent}  test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:${HERMES_API_PORT}/health')"]
${indent}  interval: 10s
${indent}  timeout: 5s
${indent}  retries: 12
${indent}  start_period: 30s`;
}

/**
 * Base docker-compose template for a single Hermes API runtime.
 * Hermes owns /opt/data; claw-farm mounts ./hermes there and must preserve it by
 * default because it contains memory, sessions, auth state, skills, and DB files.
 */
export function hermesComposeTemplate(
  name: string,
  port: number,
  _proxyMode: ProxyMode = "none",
  gatewayAllowAllUsers = false,
): string {
  safeYamlIdentifier(name, "project name");
  return `# Generated by claw-farm — ${name} (hermes)
services:
  hermes-agent:
    container_name: ${name}-hermes
    image: ${HERMES_IMAGE}
    ports:
      - "127.0.0.1:${port}:${HERMES_API_PORT}"
    volumes:
      - ./hermes:/opt/data
    env_file:
      - ./.env
      - ./.env.model
    environment:
${hermesEnvironment("      ", gatewayAllowAllUsers)}
    command: ["gateway", "run"]
${healthcheck()}
    restart: unless-stopped
`;
}

/**
 * Per-instance docker-compose for Hermes multi-instance projects.
 * Each instance has an isolated /opt/data mount and host port.
 *
 * #159B: When enableWeixinSidecar is true, a weixin-sidecar service is added
 * to the compose, consuming WEIXIN_BINDING_TOKEN from the per-instance env file.
 */
export function hermesInstanceComposeTemplate(
  projectName: string,
  userId: string,
  port: number,
  _proxyMode: ProxyMode = "none",
  instanceHostDir?: string,
  gatewayAllowAllUsers = false,
  enableWeixinSidecar = false,
  weixinEnvFile = ".env.weixin",
  weixinSidecarPort = 8787,
): string {
  safeYamlIdentifier(projectName, "project name");
  safeYamlIdentifier(userId, "user ID");
  const containerPrefix = `${projectName}-${userId}`;
  const hermesMountSource = instanceHostDir ? `${instanceHostDir}/hermes` : "./hermes";

  // #159B: weixin sidecar service definition (conditional)
  const weixinSidecarService = enableWeixinSidecar ? `  weixin-sidecar:
    container_name: ${containerPrefix}-weixin
    build: ../../claw-sidecar-weixin
    env_file:
      - ./${weixinEnvFile}
      - ./instance.env
    environment:
      SIDECAR_GATEWAY_URL: http://host.docker.internal:3002
      GATEWAY_INTERNAL_TOKEN: \${GATEWAY_INTERNAL_TOKEN:-gateway-dev-token}
      SIDECAR_CLAW_BAY_API_URL: http://host.docker.internal:3001
      WEIXIN_ENABLE_ILINK_TRANSPORT: \${WEIXIN_ENABLE_ILINK_TRANSPORT:-false}
    ports:
      - "127.0.0.1:${weixinSidecarPort}:8787"
    volumes:
      - ${hermesMountSource}/workspace/runtime/sidecar-weixin:/data
    networks:
      - sidecar-net
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:8787/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

` : "";

  // #159B: sidecar-net network when weixin sidecar is enabled
  const networksSection = enableWeixinSidecar
    ? "\nnetworks:\n  sidecar-net:\n    # Bridge network for per-instance weixin sidecar isolation\n"
    : "";

  return `# Generated by claw-farm — ${projectName} instance: ${userId} (hermes)
services:
  hermes-agent:
    container_name: ${containerPrefix}-hermes
    image: ${HERMES_IMAGE}
    ports:
      - "127.0.0.1:${port}:${HERMES_API_PORT}"
    volumes:
      - ${hermesMountSource}:/opt/data
    env_file:
      - ./instance.env
      - ./.env.model
    environment:
${hermesEnvironment("      ", gatewayAllowAllUsers)}
    command: ["gateway", "run"]
${healthcheck()}
    restart: unless-stopped
${weixinSidecarService}${networksSection}`;
}
