import type { ProxyMode } from "../runtimes/interface.ts";

/**
 * Base docker-compose template for picoclaw: picoclaw + API Proxy.
 * ~75x lighter than OpenClaw (~20MB vs ~1.5GB per instance).
 */
export function picoClawComposeTemplate(name: string, port: number, proxyMode: ProxyMode = "shared"): string {
  const hasProxy = proxyMode !== "none";
  return `# Generated by claw-farm — ${name} (picoclaw)
services:
${hasProxy ? `  api-proxy:
    build: ./api-proxy
    expose:
      - "8080"
    environment:
      LLM_PROVIDER: \${LLM_PROVIDER:-gemini}
      GEMINI_API_KEY: \${GEMINI_API_KEY:-}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:-}
      OPENAI_API_KEY: \${OPENAI_API_KEY:-}
      OPENAI_COMPAT_BASE_URL: \${OPENAI_COMPAT_BASE_URL:-}
      AUDIT_LOG_PATH: /logs/api-proxy-audit.jsonl
      MAX_PROMPT_SIZE_MB: 5
      PII_MODE: redact
    volumes:
      - ./logs:/logs
    networks:
      - proxy-net
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

` : ""}  picoclaw-gateway:
    image: ghcr.io/sipeed/picoclaw:latest
    ports:
      - "127.0.0.1:${port}:18790"
    volumes:
      - ./picoclaw:/root/.picoclaw
${hasProxy ? `    environment:
      PICOCLAW_PROXY_URL: http://api-proxy:8080
    networks:
      - proxy-net` : ""}
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 18790 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
${hasProxy ? `    depends_on:
      api-proxy:
        condition: service_healthy` : ""}
    restart: unless-stopped
${hasProxy ? `
networks:
  proxy-net:` : ""}
`;
}

/**
 * Per-instance docker-compose for picoclaw multi-instance (proxyMode=per-instance or none).
 * Each user gets their own picoclaw container + optional api-proxy.
 */
export function picoClawInstanceComposeTemplate(
  projectName: string,
  userId: string,
  port: number,
  proxyMode: ProxyMode = "per-instance",
): string {
  const containerPrefix = `${projectName}-${userId}`;
  const hasProxy = proxyMode !== "none";
  return `# Generated by claw-farm — ${projectName} instance: ${userId} (picoclaw)
services:
${hasProxy ? `  api-proxy:
    container_name: ${containerPrefix}-api-proxy
    build: ../../api-proxy
    expose:
      - "8080"
    env_file:
      - ../../.env
    environment:
      AUDIT_LOG_PATH: /logs/api-proxy-audit.jsonl
      MAX_PROMPT_SIZE_MB: 5
      PII_MODE: redact
    volumes:
      - ./logs:/logs
    networks:
      - proxy-net
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

` : ""}  picoclaw-gateway:
    container_name: ${containerPrefix}-picoclaw
    image: ghcr.io/sipeed/picoclaw:latest
    ports:
      - "127.0.0.1:${port}:18790"
    volumes:
      - ./picoclaw:/root/.picoclaw
${hasProxy ? `    environment:
      PICOCLAW_PROXY_URL: http://api-proxy:8080
    networks:
      - proxy-net` : ""}
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 18790 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
${hasProxy ? `    depends_on:
      api-proxy:
        condition: service_healthy` : ""}
    restart: unless-stopped
${hasProxy ? `
networks:
  proxy-net:` : ""}
`;
}

/**
 * Per-instance docker-compose for picoclaw (proxyMode=shared).
 * Only picoclaw container — api-proxy is shared at project level.
 *
 * Security: Each instance gets its own bridge network that connects ONLY to the
 * shared api-proxy container. Instances cannot reach each other — hub-and-spoke
 * topology prevents cross-tenant network access.
 */
export function picoClawInstanceSharedProxyComposeTemplate(
  projectName: string,
  userId: string,
  port: number,
): string {
  const containerPrefix = `${projectName}-${userId}`;
  return `# Generated by claw-farm — ${projectName} instance: ${userId} (picoclaw, shared proxy)
services:
  picoclaw-gateway:
    container_name: ${containerPrefix}-picoclaw
    image: ghcr.io/sipeed/picoclaw:latest
    ports:
      - "127.0.0.1:${port}:18790"
    volumes:
      - ./picoclaw:/root/.picoclaw
    environment:
      PICOCLAW_PROXY_URL: http://${projectName}-api-proxy:8080
    networks:
      - instance-net
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 18790 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  instance-net:
    # Per-instance isolated network. Docker Compose prefixes with project name,
    # so the actual network is "${projectName}-${userId}_instance-net".
    # The shared api-proxy is connected dynamically via "docker network connect".
    # Each instance has its own network — no cross-tenant access possible.
`;
}

/**
 * Shared api-proxy compose for picoclaw (proxyMode=shared).
 * One api-proxy serves all instances in the project.
 */
export function picoClawProxyComposeTemplate(name: string): string {
  return `# Generated by claw-farm — ${name} shared api-proxy (picoclaw)
services:
  api-proxy:
    container_name: ${name}-api-proxy
    build: ./api-proxy
    expose:
      - "8080"
    environment:
      LLM_PROVIDER: \${LLM_PROVIDER:-gemini}
      GEMINI_API_KEY: \${GEMINI_API_KEY:-}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:-}
      OPENAI_API_KEY: \${OPENAI_API_KEY:-}
      OPENAI_COMPAT_BASE_URL: \${OPENAI_COMPAT_BASE_URL:-}
      AUDIT_LOG_PATH: /logs/api-proxy-audit.jsonl
      MAX_PROMPT_SIZE_MB: 5
      PII_MODE: redact
    volumes:
      - ./logs:/logs
    networks:
      - ${name}-proxy-net
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

networks:
  ${name}-proxy-net:
`;
}
