import type { ProxyMode } from "../runtimes/interface.ts";
import { safeYamlIdentifier } from "../lib/validate.ts";

const HERMES_IMAGE = "nousresearch/hermes-agent:latest";
const HERMES_API_PORT = 8642;

function hermesEnvironment(indent = "      "): string {
  return [
    `${indent}HERMES_HOME: /opt/data`,
    `${indent}API_SERVER_ENABLED: "true"`,
    `${indent}API_SERVER_HOST: 0.0.0.0`,
    `${indent}API_SERVER_KEY: \${API_SERVER_KEY:?Set API_SERVER_KEY for Hermes API access}`,
    `${indent}GATEWAY_ALLOW_ALL_USERS: "false"`,
  ].join("\n");
}

function healthcheck(indent = "    "): string {
  return `${indent}healthcheck:
${indent}  test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:${HERMES_API_PORT}/health')"]
${indent}  interval: 10s
${indent}  timeout: 5s
${indent}  retries: 12
${indent}  start_period: 30s`;
}

/**
 * Base docker-compose template for a single Hermes API runtime.
 * Hermes owns /opt/data; claw-farm mounts ./hermes there and must preserve it by
 * default because it contains memory, sessions, auth state, skills, and DB files.
 */
export function hermesComposeTemplate(
  name: string,
  port: number,
  _proxyMode: ProxyMode = "none",
): string {
  safeYamlIdentifier(name, "project name");
  return `# Generated by claw-farm — ${name} (hermes)
services:
  hermes-agent:
    container_name: ${name}-hermes
    image: ${HERMES_IMAGE}
    ports:
      - "127.0.0.1:${port}:${HERMES_API_PORT}"
    volumes:
      - ./hermes:/opt/data
    env_file:
      - ./.env
      - ./.env.model
    environment:
${hermesEnvironment()}
    command: ["gateway", "run"]
${healthcheck()}
    restart: unless-stopped
`;
}

/**
 * Per-instance docker-compose for Hermes multi-instance projects.
 * Each instance has an isolated /opt/data mount and host port.
 */
export function hermesInstanceComposeTemplate(
  projectName: string,
  userId: string,
  port: number,
  _proxyMode: ProxyMode = "none",
  instanceHostDir?: string,
): string {
  safeYamlIdentifier(projectName, "project name");
  safeYamlIdentifier(userId, "user ID");
  const containerPrefix = `${projectName}-${userId}`;
  const hermesMountSource = instanceHostDir ? `${instanceHostDir}/hermes` : "./hermes";
  return `# Generated by claw-farm — ${projectName} instance: ${userId} (hermes)
services:
  hermes-agent:
    container_name: ${containerPrefix}-hermes
    image: ${HERMES_IMAGE}
    ports:
      - "127.0.0.1:${port}:${HERMES_API_PORT}"
    volumes:
      - ${hermesMountSource}:/opt/data
    env_file:
      - ./instance.env
      - ./.env.model
    environment:
${hermesEnvironment()}
    command: ["gateway", "run"]
${healthcheck()}
    restart: unless-stopped
`;
}
