import { portRange } from "../lib/ports.ts";
import { safeYamlIdentifier } from "../lib/validate.ts";

/**
 * Mem0+Qdrant docker-compose template: 4-tier stack with API proxy.
 * Security: API key isolated in proxy, network isolation, read-only rootfs, PII filtering.
 *
 * Network topology:
 *   openclaw ──(proxy-net)──→ api-proxy ──→ Gemini API (key injected here)
 *   openclaw ──(frontend)──→ mem0-api ──(backend)──→ qdrant
 *
 * OpenClaw has NO direct internet access and NO API keys.
 */
export function mem0ComposeTemplate(name: string, port: number): string {
  safeYamlIdentifier(name, "project name");
  const ports = portRange(port);
  return `# Generated by claw-farm — ${name} (mem0 processor)
services:
  api-proxy:
    build: ./api-proxy
    expose:
      - "8080"
    environment:
      LLM_PROVIDER: \${LLM_PROVIDER:-gemini}
      GEMINI_API_KEY: \${GEMINI_API_KEY:-}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:-}
      OPENAI_API_KEY: \${OPENAI_API_KEY:-}
      OPENAI_COMPAT_BASE_URL: \${OPENAI_COMPAT_BASE_URL:-}
      AUDIT_LOG_PATH: /logs/api-proxy-audit.jsonl
      MAX_PROMPT_SIZE_MB: 5
      PII_MODE: redact  # redact | block | warn
    volumes:
      - ./logs:/logs
    networks:
      - proxy-net
    read_only: true
    tmpfs:
      - /tmp:size=50M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.13.0
    expose:
      - "6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  mem0-api:
    build: ./mem0
    ports:
      - "127.0.0.1:${ports.mem0}:8050"
    environment:
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      MEM0_API_KEY: \${MEM0_API_KEY}
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    networks:
      - frontend
      - backend
    read_only: true
    tmpfs:
      - /tmp:size=100M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8050/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "127.0.0.1:${ports.openclaw}:18789"
    volumes:
      # Directory mount — OpenClaw needs atomic rename for config updates
      - ./openclaw:/home/node/.openclaw
    environment:
      # No GEMINI_API_KEY — agent cannot see it
      OPENCLAW_API_PROXY: http://api-proxy:8080
      OPENCLAW_SANDBOX: 1
      OPENCLAW_AUDIT_LOG: /home/node/.openclaw/logs/audit.jsonl
    networks:
      - proxy-net
      - frontend
    read_only: true
    tmpfs:
      - /tmp:size=100M
      - /home/node/.cache:size=200M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 256M
    depends_on:
      api-proxy:
        condition: service_healthy
      mem0-api:
        condition: service_healthy
    restart: unless-stopped

networks:
  proxy-net:
    internal: false   # api-proxy needs outbound to Gemini
  frontend:
    internal: true    # openclaw ↔ mem0 only
  backend:
    internal: true    # mem0 ↔ qdrant only
`;
}
