/**
 * Nginx reverse proxy config for cloud deployment.
 * Adds auth, rate limiting, and TLS termination in front of OpenClaw.
 *
 * In cloud:compose, nginx is the only container with a published port.
 * openclaw sits on an internal network — nginx proxies to it.
 */
import { safeYamlIdentifier } from "../lib/validate.ts";

export function nginxProxyTemplate(
  projects: Array<{ name: string; port: number; containerName: string }>,
): string {
  for (const p of projects) {
    safeYamlIdentifier(p.name, "project name");
    safeYamlIdentifier(p.containerName, "container name");
  }
  const upstreams = projects
    .map(
      (p) => `upstream ${p.name.replace(/-/g, "_")} {
    server ${p.containerName}:18789;
}`,
    )
    .join("\n\n");

  const servers = projects
    .map(
      (p) => `server {
    listen ${p.port};

    # Security headers
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    # Rate limiting
    limit_req zone=global burst=20 nodelay;
    limit_req_status 429;

    # Request size limit
    client_max_body_size 10M;

    location / {
        proxy_pass http://${p.name.replace(/-/g, "_")};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeouts for long-running LLM requests
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    # Block direct access to internal APIs
    location /internal/ {
        deny all;
        return 404;
    }
}`,
    )
    .join("\n\n");

  return `# Generated by claw-farm cloud:compose
# Place behind Coolify's built-in SSL or use certbot for standalone TLS

limit_req_zone $binary_remote_addr zone=global:10m rate=10r/s;

${upstreams}

${servers}
`;
}

/**
 * Nginx Dockerfile for cloud deployment.
 */
export function nginxDockerfileTemplate(): string {
  return `FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
`;
}
