/**
 * OpenClaw configuration template.
 * Routes LLM calls through api-proxy (no direct API key access).
 */
export function openclawConfigTemplate(
  name: string,
  processor: "builtin" | "mem0",
): string {
  const plugins =
    processor === "mem0"
      ? `
  // Mem0 memory plugin
  "plugins": [
    {
      "name": "mem0",
      "type": "memory",
      "endpoint": "http://mem0-api:8050",
      "autoSave": true,
      "autoRecall": true
    }
  ],
`
      : "";

  return `{
  // OpenClaw config — ${name} (generated by claw-farm)
  // Schema: OpenClaw 2026.3.23+

  // Agent model configuration
  "agents": {
    "defaults": {
      "model": {
        "primary": "google/gemini-2.5-flash"
      }
    }
  },

  // LLM provider — routes through api-proxy (no direct API key access)
  "models": {
    "providers": {
      "google": {
        "baseUrl": "http://api-proxy:8080/v1beta"
      }
    }
  },

  // API key is NOT here — it's isolated in api-proxy.
  // env.GEMINI_API_KEY is a placeholder so OpenClaw doesn't complain about missing key.
  "env": {
    "GEMINI_API_KEY": "proxied"
  },
${plugins}
  // Gateway — bind to LAN so Docker port-forwarding works
  "gateway": {
    "bind": "lan",
    "port": 18789
  },

  // Control UI disabled to reduce memory usage (SEA binary V8 heap limit)
  "controlUi": {
    "enabled": false
  }
}
`;
}
