/**
 * OpenClaw configuration template.
 * Routes LLM calls through api-proxy (no direct API key access).
 */
export function openclawConfigTemplate(
  name: string,
  processor: "builtin" | "mem0",
): string {
  const plugins =
    processor === "mem0"
      ? `
  // Mem0 memory plugin
  "plugins": [
    {
      "name": "mem0",
      "type": "memory",
      "endpoint": "http://mem0-api:8050",
      "autoSave": true,
      "autoRecall": true
    }
  ],
`
      : "";

  return `{
  // OpenClaw config — ${name} (generated by claw-farm)
  "model": "gemini-2.5-flash",
  "provider": "gemini",

  // API key is NOT here — it's isolated in api-proxy.
  // OpenClaw routes LLM calls through the proxy which injects the key.
  "apiBaseUrl": "http://api-proxy:8080",
  "apiKey": "proxied",
${plugins}
  // Dashboard
  "dashboard": {
    "port": 18789,
    "host": "0.0.0.0"
  }
}
`;
}
