/**
 * OpenClaw policy.yaml template — tool access restrictions.
 * Controls what the agent can and cannot do.
 */
export function policyTemplate(name: string): string {
  return `# OpenClaw Security Policy — ${name}
# Generated by claw-farm. Edit to match your agent's needs.

# Tool access control
tools:
  # File system: restrict to workspace only
  filesystem:
    allow:
      - /home/node/.openclaw/workspace/**
      - /home/node/.openclaw/sessions/**
    deny:
      - /home/node/.openclaw/config/**   # no config tampering
      - /etc/**
      - /proc/**
      - /sys/**

  # Network: allowlist domains the agent's HTTP tool can reach
  # NOTE: LLM calls go through api-proxy (internal Docker network),
  # NOT through this HTTP tool. This only restricts web_fetch/web_search tools.
  http:
    allow:
      # Add domains your agent needs to access via tools
      # - api.example.com
      # - "*.googleapis.com"
    deny:
      - "*"  # deny all by default, add allows above

  # Shell: disabled by default (agent shouldn't run arbitrary commands)
  shell:
    enabled: false

  # Code execution: sandboxed only
  code_execution:
    sandbox: true
    timeout_seconds: 30

# Rate limits (per minute)
rate_limits:
  tool_calls: 60
  llm_requests: 30
  memory_writes: 20

# Audit logging
audit:
  enabled: true
  log_tool_calls: true
  log_llm_requests: false   # too verbose, enable for debugging
  log_memory_ops: true
  format: jsonl
`;
}
